name: C/C++ CI

on:
  push:
    branches: [ main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: compile
      run: gcc main.c -o main
    - name: run
      run: ./main
